profile: null
region: ap-northeast-1
versioning: false
default_alias: master
configuration:
  name: kipi-slack-bot
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: slack_bot.lambda_handler
  description: Kipi Slack Bot
  timeout: 30
  memory_size: 128
